# cat(length(fwbw_res$F1),"\n")
# cat("range(fwbw_res$F1) : ",range(fwbw_res$F1),"\n")
# cat("any(is.nan(fwbw_res$F1)) : ",any(is.nan(fwbw_res$F1)),"\n")
# cat("any(is.nan(fwbw_res$N)) : ",any(is.nan(fwbw_res$N)),"\n")
# cat("any(is.nan(fwbw_res$si)) : ",any(is.nan(fwbw_res$si)),"\n")
# cat("any(is.nan(fwbw_res$G))  : ",any(is.nan(fwbw_res$G)),"\n")
# cat("any(is.nan(fwbw_res$L1)) : ",any(is.nan(fwbw_res$L1)),"\n")
#
# cat("all(is.nan(fwbw_res$F1)) : ",all(is.nan(fwbw_res$F1)),"\n")
# F1 = matrix(fwbw_res$F1, ncol = J)
# matplot(F1, type = "l", lty = 1, col = model$state_colors)
# cat("all(is.nan(fwbw_res$F1)) : ",all(is.nan(fwbw_res$F1)),"\n")
# cat("apply(F1, 2, function(x) any(is.nan(x))) : ", apply(F1, 2, function(x) any(is.nan(x))), "\n")
# cat("apply(F1, 2, function(x) sum(is.nan(x))) : ", apply(F1, 2, function(x) sum(is.nan(x))), "\n")
# matplot(is.nan(F1), type = "l", lty = 1, col = model$state_colors)
# plot(apply(F1,1, sum), type = "l")
#
# plot(fwbw_res$N, type = "l", ylim = c(0,0.001))
# cat("range(fwbw_res$N)",range(fwbw_res$N), "\n")
#
# G = matrix(fwbw_res$G, ncol = J)
# cat("all(is.nan(G)) : ",all(is.nan(G)),"\n")
# cat("apply(G, 2, function(x) any(is.nan(x))) : ", apply(G, 2, function(x) any(is.nan(x))), "\n")
# cat("apply(G, 2, function(x) sum(is.nan(x))) : ", apply(G, 2, function(x) sum(is.nan(x))), "\n")
# matplot(is.nan(G), type = "l", lty = 1, col = model$state_colors)
